name: Security Scan

# This workflow will run on every pushed commit and pull requests to check for vulnerabilities.
on: [push, pull_request]

jobs:
    Scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: TruffleHog Enterprise scan
              uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
